/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistRouteImport } from './routes/artist'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as DecreeRouteImport } from './routes/decree'
import { Route as FieldRouteImport } from './routes/field'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as LabelRouteImport } from './routes/label'
import { Route as LatticeRouteImport } from './routes/lattice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RhythmRouteImport } from './routes/rhythm'
import { Route as StryderRouteImport } from './routes/stryder'
import { Route as TrackSlugRouteImport } from './routes/track.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistRoute = ArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const DecreeRoute = DecreeRouteImport.update({
  id: '/decree',
  path: '/decree',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => rootRouteImport,
} as any)
const LatticeRoute = LatticeRouteImport.update({
  id: '/lattice',
  path: '/lattice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RhythmRoute = RhythmRouteImport.update({
  id: '/rhythm',
  path: '/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const StryderRoute = StryderRouteImport.update({
  id: '/stryder',
  path: '/stryder',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSlugRoute = TrackSlugRouteImport.update({
  id: '/track/$slug',
  path: '/track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/catalog': typeof CatalogRoute
  '/crash': typeof CrashRoute
  '/decree': typeof DecreeRoute
  '/field': typeof FieldRoute
  '/harvest': typeof HarvestRoute
  '/label': typeof LabelRoute
  '/lattice': typeof LatticeRoute
  '/login': typeof LoginRoute
  '/rhythm': typeof RhythmRoute
  '/stryder': typeof StryderRoute
  '/track/$slug': typeof TrackSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/catalog': typeof CatalogRoute
  '/crash': typeof CrashRoute
  '/decree': typeof DecreeRoute
  '/field': typeof FieldRoute
  '/harvest': typeof HarvestRoute
  '/label': typeof LabelRoute
  '/lattice': typeof LatticeRoute
  '/login': typeof LoginRoute
  '/rhythm': typeof RhythmRoute
  '/stryder': typeof StryderRoute
  '/track/$slug': typeof TrackSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist': typeof ArtistRoute
  '/catalog': typeof CatalogRoute
  '/crash': typeof CrashRoute
  '/decree': typeof DecreeRoute
  '/field': typeof FieldRoute
  '/harvest': typeof HarvestRoute
  '/label': typeof LabelRoute
  '/lattice': typeof LatticeRoute
  '/login': typeof LoginRoute
  '/rhythm': typeof RhythmRoute
  '/stryder': typeof StryderRoute
  '/track/$slug': typeof TrackSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artist'
    | '/catalog'
    | '/crash'
    | '/decree'
    | '/field'
    | '/harvest'
    | '/label'
    | '/lattice'
    | '/login'
    | '/rhythm'
    | '/stryder'
    | '/track/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artist'
    | '/catalog'
    | '/crash'
    | '/decree'
    | '/field'
    | '/harvest'
    | '/label'
    | '/lattice'
    | '/login'
    | '/rhythm'
    | '/stryder'
    | '/track/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/artist'
    | '/catalog'
    | '/crash'
    | '/decree'
    | '/field'
    | '/harvest'
    | '/label'
    | '/lattice'
    | '/login'
    | '/rhythm'
    | '/stryder'
    | '/track/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistRoute: typeof ArtistRoute
  CatalogRoute: typeof CatalogRoute
  CrashRoute: typeof CrashRoute
  DecreeRoute: typeof DecreeRoute
  FieldRoute: typeof FieldRoute
  HarvestRoute: typeof HarvestRoute
  LabelRoute: typeof LabelRoute
  LatticeRoute: typeof LatticeRoute
  LoginRoute: typeof LoginRoute
  RhythmRoute: typeof RhythmRoute
  StryderRoute: typeof StryderRoute
  TrackSlugRoute: typeof TrackSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist': {
      id: '/artist'
      path: '/artist'
      fullPath: '/artist'
      preLoaderRoute: typeof ArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decree': {
      id: '/decree'
      path: '/decree'
      fullPath: '/decree'
      preLoaderRoute: typeof DecreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label': {
      id: '/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lattice': {
      id: '/lattice'
      path: '/lattice'
      fullPath: '/lattice'
      preLoaderRoute: typeof LatticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rhythm': {
      id: '/rhythm'
      path: '/rhythm'
      fullPath: '/rhythm'
      preLoaderRoute: typeof RhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stryder': {
      id: '/stryder'
      path: '/stryder'
      fullPath: '/stryder'
      preLoaderRoute: typeof StryderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$slug': {
      id: '/track/$slug'
      path: '/track/$slug'
      fullPath: '/track/$slug'
      preLoaderRoute: typeof TrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistRoute: ArtistRoute,
  CatalogRoute: CatalogRoute,
  CrashRoute: CrashRoute,
  DecreeRoute: DecreeRoute,
  FieldRoute: FieldRoute,
  HarvestRoute: HarvestRoute,
  LabelRoute: LabelRoute,
  LatticeRoute: LatticeRoute,
  LoginRoute: LoginRoute,
  RhythmRoute: RhythmRoute,
  StryderRoute: StryderRoute,
  TrackSlugRoute: TrackSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
